// Per-session Posts state.
// Mirrors the subscribe/notify pattern used by src/library.js.
//
// Public API:
//   getPosts(sessionId)         → Post[]  (seeds from mocks on first access)
//   addPostDraft(sessionId, {network, text[], hashtags[]}) → Post
//   attachImageToDraft(sessionId, postId, imageUrl)
//   subscribe(sessionId, fn)    → unsubscribe fn

import { postsBySession as seedPostsBySession, allSeedSessions as seedRecentSessions } from "./mocks.js?v=1029";
import { isNewUser } from "./user-mode.js?v=1029";
import { createSessionNotifier } from "./store-utils.js?v=1029";

// Demo session ids — only these get the seeded posts mock. Brand-new
// conversations start empty (cf. library.js for the same rationale).
const DEMO_SESSION_IDS = new Set(seedRecentSessions.map((s) => s.id));

// --- Module state -------------------------------------------------------

const store = new Map(); // sessionId → Post[]
const notifier = createSessionNotifier("posts-store");

let idCounter = 0;
function newId() {
  idCounter += 1;
  return `draft-${Date.now().toString(36)}-${idCounter}`;
}

// --- Public API ---------------------------------------------------------

export function getPosts(sessionId) {
  if (!store.has(sessionId)) seed(sessionId);
  return store.get(sessionId);
}

// Prepend a new draft post (generated by the conversational draft flow).
// Returns the created post object so callers can reference its id.
export function addPostDraft(
  sessionId,
  { network, text, hashtags = [], clipRef = null, subtitleStyle = null, format = null, language = null },
) {
  const posts = getPosts(sessionId);
  // Use the first existing post's author as a template — keeps the demo
  // looking like it belongs to the same person.
  const templateAuthor = posts[0]?.author || {
    name: "You",
    title: "",
    initials: "YO",
    connection: "1st",
    visibility: "public",
  };
  const draft = {
    id: newId(),
    author: templateAuthor,
    network: network === "x" ? "twitter" : network,
    status: "ready",
    timeLabel: "just now",
    // The language this draft was generated in — defaults to the Playbook's
    // primary language when the draft flow doesn't ask. Null for legacy drafts.
    language: language || null,
    text: Array.isArray(text) ? text : [text],
    hashtags,
    cta: "",
    hasImage: false,
    stats: { likes: 0, comments: 0, reposts: 0 },
    // Optional video-source reference — set by the Video Clips modal so the
    // post card renders a native-feeling video player in place of the
    // "Generate an image" placeholder. `hue` drives the faux thumbnail's
    // gradient color so the demo looks like a real frame extraction.
    clipRef: clipRef
      ? {
          start: clipRef.start,
          end: clipRef.end,
          sourceName: clipRef.sourceName,
          hue: typeof clipRef.hue === "number" ? clipRef.hue : 24,
          // Back-references to the source clip so the post card can reopen it
          // in the Video Clips modal for editing. Null for legacy/manual refs.
          sourceId: clipRef.sourceId || null,
          clipId: clipRef.clipId || null,
        }
      : null,
    // Subtitle preset chosen by the user after the "Add subtitles?" turn.
    // Only meaningful when clipRef is set; carries the style name so the
    // post-card can show a "Subtitles · Bold" metadata pill under the
    // video PIP. `null` or "none" → no badge.
    subtitleStyle: subtitleStyle || null,
    // Export aspect ratio chosen in the clip-draft flow (e.g. "9:16").
    // Only meaningful when clipRef is set; the post-card uses it to pick a
    // portrait vs landscape video frame. `null` → fall back to the
    // network's default orientation.
    format: format || null,
  };
  posts.unshift(draft);
  notify(sessionId);
  return draft;
}

// Apply a subtitle style preset to one or many existing drafts. Used by
// the "Add subtitles to your clips?" question that posts in the assistant
// thread after the user has drafted N posts from clips. `style` is one of
// "bold" | "clean" | "caption" | "none" (or null to clear).
export function setSubtitleStyle(sessionId, postIds, style) {
  const posts = getPosts(sessionId);
  const ids = Array.isArray(postIds) ? postIds : [postIds];
  let touched = false;
  for (const id of ids) {
    const post = posts.find((p) => p.id === id);
    if (post) {
      post.subtitleStyle = style === "none" ? null : style || null;
      touched = true;
    }
  }
  if (touched) notify(sessionId);
}

// Re-sync a draft's denormalized clip fields after the user edits the
// underlying clip in the Video Clips modal (trim window, export format,
// subtitle style). Leaves text / hashtags untouched — only the video-PIP
// metadata changes. `subtitleStyle` accepts a caption-preset id or "none".
export function updatePostClip(sessionId, postId, { start, end, format, subtitleStyle } = {}) {
  const posts = getPosts(sessionId);
  const post = posts.find((p) => p.id === postId);
  if (!post || !post.clipRef) return;
  if (typeof start === "number") post.clipRef.start = start;
  if (typeof end === "number") post.clipRef.end = end;
  if (format !== undefined) post.format = format || null;
  if (subtitleStyle !== undefined) post.subtitleStyle = subtitleStyle === "none" ? null : subtitleStyle || null;
  notify(sessionId);
}

// Update a post's image (called from the generate-image modal callback). A
// single image clears any carousel — the two are mutually exclusive.
export function attachImageToDraft(sessionId, postId, imageUrl) {
  const posts = getPosts(sessionId);
  const post = posts.find((p) => p.id === postId);
  if (post) {
    post.hasImage = true;
    post.imageUrl = imageUrl;
    post.carousel = null;
    notify(sessionId);
  }
}

// Attach a multi-slide carousel (generate mode, carousel output). Slide 0 doubles
// as the poster `imageUrl` so single-image render/attach paths keep working.
export function attachCarouselToDraft(sessionId, postId, urls) {
  const posts = getPosts(sessionId);
  const post = posts.find((p) => p.id === postId);
  if (post && urls && urls.length) {
    post.hasImage = true;
    post.imageUrl = urls[0];
    post.carousel = [...urls];
    notify(sessionId);
  }
}

// Patch a post's editable body fields (text[], hashtags[], cta).
// Undefined keys are left unchanged.
//
// Also accepts the runtime regenerate flags driven by draft-rewrite.js
// (`isRegenerating`, `regenerateStage`) and the one-click image flag set by
// the drafts panel (`isGeneratingImage`). These never appear in seeded
// mocks — they're transient state set during a streaming / generating flow.
// Pass `null` or `false` to clear them.
export function updatePostContent(sessionId, postId, partial) {
  const posts = getPosts(sessionId);
  const post = posts.find((p) => p.id === postId);
  if (!post) return;
  if (partial.text !== undefined) post.text = partial.text;
  if (partial.hashtags !== undefined) post.hashtags = partial.hashtags;
  if (partial.cta !== undefined) post.cta = partial.cta;
  if (partial.isRegenerating !== undefined) post.isRegenerating = partial.isRegenerating;
  if (partial.regenerateStage !== undefined) post.regenerateStage = partial.regenerateStage;
  if (partial.isGeneratingImage !== undefined) post.isGeneratingImage = partial.isGeneratingImage;
  notify(sessionId);
}

// Remove a post from the session's drafts list. Returns the removed post
// (or null) so the caller can offer Undo via re-insertion.
export function removePost(sessionId, postId) {
  const posts = getPosts(sessionId);
  const idx = posts.findIndex((p) => p.id === postId);
  if (idx < 0) return null;
  const [removed] = posts.splice(idx, 1);
  notify(sessionId);
  return removed;
}

// Re-insert a previously removed post at its original index (used by the
// Undo action of the trash-button toast).
export function insertPost(sessionId, post, index = 0) {
  const posts = getPosts(sessionId);
  posts.splice(index, 0, post);
  notify(sessionId);
}

export const subscribe = notifier.subscribe;

// Drop all posts + subscribers for a session — used by the
// conversation-delete flow in the sidebar. Subscribers get one final empty
// snapshot so mounted DOM can tear down before they're forgotten.
export function clearSession(sessionId) {
  store.delete(sessionId);
  notifier.clear(sessionId, []);
}

// --- Internals ----------------------------------------------------------

function seed(sessionId) {
  // Mirrors library.js: only demo sessions (s-acme-launch / s-riverside /
  // etc.) get the seeded posts mock. New conversations created at runtime
  // start empty so the user doesn't see "5 drafts" appear in a chat they
  // just opened from "+ New conversation".
  //
  // Pulls from the per-session bucket in mocks (`postsBySession`) so each
  // demo session has its own distinct drafts list. Shallow-copy each post
  // so edits don't leak across sessions or mutate the shared mock array.
  const shouldSeed = !isNewUser() && DEMO_SESSION_IDS.has(sessionId);
  const seedForSession = shouldSeed ? seedPostsBySession[sessionId] || [] : [];
  store.set(
    sessionId,
    seedForSession.map((p) => ({ ...p })),
  );
}

function notify(sessionId) {
  notifier.notify(sessionId, (store.get(sessionId) || []).slice());
}
